#!/usr/bin/env node
/**
 * Schoolyard token build.
 *
 * Reads tokens.json (the single source of truth) and emits two outputs:
 *   - dist/web.css   — CSS custom properties consumed by Astro/Tailwind
 *   - dist/native.ts — typed theme object consumed by NativeWind / RN
 *
 * The default `color.primary` and `color.accent` values are placeholders.
 * At runtime, the school's branding colors from school.config.json are
 * injected into the page via BaseLayout.astro, overriding these defaults.
 *
 * We use Style Dictionary's data model (tokens.json shape) but emit by
 * hand to keep the dependency surface tiny and the build deterministic
 * across environments.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const tokensPath = join(__dirname, 'tokens.json')
const distDir = join(__dirname, 'dist')

mkdirSync(distDir, { recursive: true })

const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'))

/**
 * Walk the token tree and produce a list of { path, value } leaves.
 * A leaf is any node with a `value` property.
 */
function flatten(obj, path = []) {
  const out = []
  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === 'object' && 'value' in val) {
      out.push({ path: [...path, key], value: val.value })
    } else if (val && typeof val === 'object') {
      out.push(...flatten(val, [...path, key]))
    }
  }
  return out
}

const leaves = flatten(tokens)

// ───────────────── web.css ─────────────────
const cssLines = [
  '/* AUTO-GENERATED by packages/tokens/build.js — do not edit by hand. */',
  '/* Run `pnpm tokens:build` to regenerate. */',
  ':root {',
]
for (const leaf of leaves) {
  const name = `--sy-${leaf.path.join('-')}`
  cssLines.push(`  ${name}: ${leaf.value};`)
}
cssLines.push('}')
cssLines.push('')
writeFileSync(join(distDir, 'web.css'), cssLines.join('\n'), 'utf8')

// ───────────────── native.ts ─────────────────
/**
 * Rebuild the original nested shape but with `value` collapsed to the
 * primitive at each leaf. Easier to consume from RN/NativeWind code.
 */
function collapse(obj) {
  if (obj && typeof obj === 'object' && 'value' in obj) return obj.value
  if (obj && typeof obj === 'object') {
    const out = {}
    for (const [k, v] of Object.entries(obj)) out[k] = collapse(v)
    return out
  }
  return obj
}

const nativeTokens = collapse(tokens)
const nativeLines = [
  '// AUTO-GENERATED by packages/tokens/build.js — do not edit by hand.',
  '// Run `pnpm tokens:build` to regenerate.',
  '',
  'export const tokens = ' + JSON.stringify(nativeTokens, null, 2) + ' as const',
  '',
  'export type Tokens = typeof tokens',
  '',
]
writeFileSync(join(distDir, 'native.ts'), nativeLines.join('\n'), 'utf8')

console.warn(`✅ Built ${leaves.length} tokens → dist/web.css + dist/native.ts`)
